FROM mauriciocleveland/pulzar:1.0.3

LABEL Mauricio Cleveland "mauricio.cleveland@gmail.com"
EXPOSE 31414

COPY app /usr/local/bin/pulzar
COPY app/storage/dbs /var/lib/pulzar/dbs
WORKDIR /usr/local/bin/pulzar
COPY dockers/start_master.sh start_master.sh
CMD [ "sh", "start_master.sh" ]