apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulzar-master-deployment
spec:
  selector:
    matchLabels:
      app: pulzar-master
  template:
    metadata:
      labels:
        app: pulzar-master
        project: pulzar
    spec:    
      volumes:
      - name: configpvc
        persistentVolumeClaim:
          claimName: master-volume-claim
      containers:
      - name: pulzar-master
        image: mauriciocleveland/pulzar-master:1.0.1
        volumeMounts:
          - mountPath: "/var/lib/pulzar/"
            name: configpvc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 31414
      - name: pulzar-ui
        image: mauriciocleveland/pulzar-ui:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
  
---

apiVersion: v1
kind: Service
metadata:
  name: pulzar-master-service
spec:
  selector:
    app: pulzar-master
  ports:
    - protocol: TCP
      name: service
      port: 31414
      targetPort: 31414

---

apiVersion: v1
kind: Service
metadata:
  name: pulzar-ui-service
spec:
  selector:
    app: pulzar-master
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30080