apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulzar-ui-deployment
spec:
  selector:
    matchLabels:
      app: pulzar-ui
  template:
    metadata:
      labels:
        app: pulzar-ui
    spec:
      containers:
      - name: pulzar-ui
        image: mauriciocleveland/pulzar-ui:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: pulzar-ui-service
spec:
  selector:
    app: pulzar-ui
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30080